const CARD_DATABASE = [
    { id: "0016", rank: "ss", type: "character", group: "287期受験生", name: "ゴン", cost: { specific: 4, free: 2 }, atk: 19, ability: { text: "[試験]通常ダメージが25以上になるマスに配置すれば発動。特殊ダメージを15与える。" }, combo: { text: "特殊ダメージを11与える。" } },
    { id: "0023", rank: "ss", type: "character", group: "287期受験生", name: "キルア", cost: { specific: 2, free: 1 }, atk: 13, ability: { text: "[試験]通常ダメージが16以上になるマスに配置すれば発動。特殊ダメージを9与える。" }, combo: { text: "特殊ダメージを6与える。" } },
    { id: "0032", rank: "ss", type: "character", group: "287期受験生", name: "レオリオ", cost: { specific: 2, free: 2 }, atk: 15, ability: { text: "[試験]通常ダメージが19以上になるマスに配置すれば発動。特殊ダメージを10与える。" }, combo: { text: "特殊ダメージを8与える。" } },
    { id: "0036", rank: "ss", type: "character", group: "287期受験生", name: "クラピカ", cost: { specific: 3, free: 2 }, atk: 16, ability: { text: "[試験]通常ダメージが21以上になるマスに配置すれば発動。特殊ダメージを12与える。" }, combo: { text: "特殊ダメージを10与える。" } },
    { id: "0055", rank: "ss", type: "character", group: "幻影旅団", name: "マチ", cost: { specific: 3, free: 3 }, atk: 12, ability: { text: "2枚以上ひっくり返した時、自分のHPを15回復する。" }, combo: { text: "自分のHPを10回復する。" } },
    { id: "0066", rank: "ss", type: "character", group: "幻影旅団", name: "フェイタン", cost: { specific: 2, free: 1 }, atk: 13, ability: { text: "3ターンの間、受ける通常ダメージと特殊ダメージと念ダメージを-2する。" }, combo: { text: "念ダメージを6与える。" } },
    { id: "0073", rank: "ss", type: "character", group: "幻影旅団", name: "クロロ", cost: { specific: 1, free: 0 }, atk: 5, ability: { text: "自分の「幻影旅団」のGPを1増やす。" }, combo: { text: "念ダメージを8与える。" } },
    { id: "0075", rank: "ss", type: "character", group: "幻影旅団", name: "ウボォーギン", cost: { specific: 3, free: 4 }, atk: 15, ability: { text: "周囲8マスに相手のキャラカードが1枚以上ある場合、空にする。念ダメージを13与える。" }, combo: { text: "念ダメージを10与える。" } },
    { id: "0141", rank: "ss", type: "character", group: "幻影旅団", nameTitle: "極意の発動", name: "クロロ", cost: { specific: 4, free: 4 }, atk: 30 },
    { id: "0115", rank: "ss", type: "character", group: "マフィアンコミュニティー", nameTitle: "復讐劇の幕開け", name: "クラピカ", cost: { specific: 3, free: 2 }, atk: 16, ability: { text: "HPが60以下であれば発動。念ダメージを12与える。" }, combo: { text: "念ダメージを10与える。" } },
    { id: "0046", rank: "s", type: "character", group: "幻影旅団", name: "シズク", cost: { specific: 0, free: 0 }, atk: 7, ability: { text: "自分の手札にあるカードを1枚デッキに戻す。" }, combo: { text: "念ダメージを7与える。" } },
    { id: "0048", rank: "s", type: "character", group: "幻影旅団", name: "パクノダ", cost: { specific: 0, free: 0 }, atk: 7, ability: { text: "自分の手札にあるカードを1枚デッキに戻す。" }, combo: { text: "念ダメージを7与える。" } },
    { id: "0060", rank: "s", type: "character", group: "幻影旅団", name: "ノブナガ", cost: { specific: 4, free: 0 }, atk: 8, ability: { text: "4ターンの間、受ける通常ダメージを-4にする。" }, combo: { text: "念ダメージを11与える。" } },
    { id: "0064", rank: "s", type: "character", group: "幻影旅団", name: "シャルナーク", cost: { specific: 1, free: 1 }, atk: 9, ability: { text: "相手の手札にあるキャラカードすべてのATKを-3する。" }, combo: { text: "念ダメージを8与える。" } },
    { id: "0065", rank: "s", type: "character", group: "幻影旅団", name: "マチ", cost: { specific: 4, free: 5 }, atk: 21, ability: { text: "盤面に自分のキャラカードが他に3枚以上ある場合 念ダメージを14与える。" }, combo: { text: "念ダメージを11与える。" } },
    { id: "0070", rank: "s", type: "character", group: "幻影旅団", name: "ヒソカ", cost: { specific: 5, free: 0 }, atk: 10, ability: { text: "相手の手札にあるキャラカード1枚のATKを-10にする。" }, combo: { text: "念ダメージを10与える。" } },
    { id: "0079", rank: "s", type: "character", group: "幻影旅団", nameTitle: "マフィアの一掃", name: "フランクリン", cost: { specific: 4, free: 7 }, atk: 26, ability: { text: "盤面に自分の「幻影旅団」のキャラカードが他に3枚以上ある場合、念ダメージを18与える。" }, combo: { text: "念ダメージを11与える。" } },
    { id: "0160", rank: "s", type: "character", group: "幻影旅団", name: "フィンクス", cost: { specific: 3, free: 3 }, atk: 20, ability: { text: "3枚以上ひっくり返した時、念ダメージを10与える。" }, combo: { text: "念ダメージを10与える。" } },
    { id: "0183", rank: "s", type: "character", group: "幻影旅団", name: "ウボォーギン", cost: { specific: 3, free: 4 }, atk: 19, ability: { text: "キャラカードをひっくり返した時、念ダメージを5与える。" }, combo: { text: "念ダメージを10与える。" } },
    { id: "0188", rank: "s", type: "character", group: "幻影旅団", nameTitle: "ウボォーさん、聞こえますか？", name: "クロロ", cost: { specific: 3, free: 3 }, atk: 20, ability: { text: "自分の捨て場に「ウボォーギン」のキャラカードが1枚以上あれば発動。自分の「幻影旅団」のGPを1増やす。" }, combo: { text: "念ダメージを10与える。" } },
    { id: "0120", rank: "ss", type: "character", group: "マフィアンコミュニティー", nameTitle: "百発百中の占い師", name: "ネオン", cost: { specific: 1, free: 0 }, atk: 10, combo: { text: "念ダメージを8与える。" } },
    { id: "0121", rank: "ss", type: "character", group: "マフィアンコミュニティー", nameTitle: "心の旋律", name: "センリツ", cost: { specific: 3, free: 3 }, atk: 18, ability: { text: "HPが60以下であれば発動。自分のHPを10回復する。" } },
    { id: "0123", rank: "ss", type: "character", group: "マフィアンコミュニティー", nameTitle: "流離の大俳人", name: "バショウ", cost: { specific: 3, free: 3 }, atk: 18, ability: { text: "HPが60以下であれば発動。念ダメージを13与える。" }, combo: { text: "特殊ダメージを11与える。" } },
    { id: "0002", rank: "s", type: "character", group: "287期受験生", name: "ポンズ", cost: { specific: 0, free: 0 }, atk: 7, ability: { text: "自分の手札にあるキャラカード1枚のATKを+3する。" }, combo: { text: "特殊ダメージを6与える。" } },
    { id: "0003", rank: "s", type: "character", group: "287期受験生", name: "レオリオ", cost: { specific: 1, free: 0 }, atk: 10, ability: { text: "3ターンの間、ターン開始時に自分の手札にあるランダムなキャラカード1枚のATKを+2する。" }, combo: { text: "特殊ダメージを8与える。" } },
    { id: "0004", rank: "s", type: "character", group: "287期受験生", name: "ボドロ", cost: { specific: 0, free: 0 }, atk: 7, ability: { text: "自分の手札にあるカードを1枚捨てる。" }, combo: { text: "特殊ダメージを7与える。" } },
    { id: "0010", rank: "s", type: "character", group: "287期受験生", name: "トンパ", cost: { specific: 0, free: 0 }, atk: 7, ability: { text: "自分の手札にあるカードを1枚捨てる。" }, combo: { text: "特殊ダメージを7与える。" } },
    { id: "0022", rank: "s", type: "character", group: "287期受験生", name: "キルア", cost: { specific: 1, free: 0 }, atk: 11, ability: { text: "[試験]通常ダメージが12以上になるマスに配置すれば発動。特殊ダメージを2与える。" }, combo: { text: "特殊ダメージを8与える。" } },
    { id: "0028", rank: "s", type: "character", group: "287期受験生", name: "ポックル", cost: { specific: 2, free: 1 }, atk: 9, ability: { text: "自分の手札にあるランダムなキャラカード2枚のATKを+5する。" }, combo: { text: "特殊ダメージを9与える。" } },
    { id: "0031", rank: "s", type: "character", group: "287期受験生", name: "イルミ", cost: { specific: 1, free: 1 }, atk: 9, ability: { text: "自分の手札にあるキャラカード1枚のATKを+5する。" }, combo: { text: "特殊ダメージを8与える。" } },
    { id: "0157", rank: "s", type: "character", group: "287期受験生", name: "ゴン", cost: { specific: 2, free: 0 }, atk: 12, ability: { text: "[試験]通常ダメージが14以上になるマスに配置すれば発動。特殊ダメージを3与える。" }, combo: { text: "特殊ダメージを8与える。" } },
    { id: "0173", rank: "s", type: "character", group: "287期受験生", nameTitle: "実りを待つ奇術師", name: "ヒソカ", cost: { specific: 3, free: 3 }, atk: 14, ability: { text: "盤面に自分の「ゴン」が1体以上いる場合発動。特殊ダメージを12与える。" }, combo: { text: "特殊ダメージを10与える。" } },
    { id: "0178", rank: "s", type: "character", group: "287期受験生", nameTitle: "命よりも意地が大切だってのか!!", name: "ハンゾー", cost: { specific: 3, free: 3 }, atk: 16, ability: { text: "盤面に自分の[287期受験生」のキャラカードが他に2枚以上ある場合、特殊ダメージを9与える。" }, combo: { text: "特殊ダメージを13与える。" } },
    { id: "0133", rank: "ss", type: "character", group: "フリー", nameTitle: "ハンター協会会長", name: "ネテロ", cost: { specific: 6, free: 0 }, atk: 10, ability: { text: "ひっくり返した後の盤面に相手のキャラカードが3枚以上ある場合、特殊ダメージを18与える。" }, combo: { text: "特殊ダメージを13与える。" } },
    { id: "0131", rank: "s", type: "character", group: "フリー", nameTitle: "窮地からの脱出", name: "ゴン", cost: { specific: 5, free: 0 }, atk: 18, ability: { text: "ひっくり返した後の周囲8マスに相手の「幻影旅団」のキャラカードが1枚以上ある場合、次の相手のターン、受ける通常ダメージを-10する。" }, combo: { text: "念ダメージを12与える。" } },
    { id: "A054", rank: "ss", type: "action", group: "幻影旅団", name: "盗賊の極意", cost: { specific: 4, free: 1 }, atk: 5 },
    { id: "A087", rank: "ss", type: "action", group: "幻影旅団", name: "幻影の鎮魂曲", cost: { specific: 2, free: 1 }, atk: 5 },
    { id: "A082", rank: "s", type: "action", group: "幻影旅団", name: "派手に殺れ!!", cost: { specific: 1, free: 1 }, atk: 5 },
    { id: "A084", rank: "s", type: "action", group: "幻影旅団", nameTitle: "アクション", name: "極悪非道の盗賊団", cost: { specific: 2, free: 0 }, atk: 5 },
    { id: "A085", rank: "s", type: "action", group: "幻影旅団", nameTitle: "アクション", name: "鎖野郎を追う者", cost: { specific: 2, free: 2 }, atk: 5 },
    { id: "A086", rank: "s", type: "action", group: "幻影旅団", nameTitle: "アクション", name: "全開だ!!!!!!", cost: { specific: 2, free: 2 }, atk: 5 },
    { id: "A083", rank: "a", type: "action", group: "幻影旅団", nameTitle: "アクション", name: "死体は偽物★-_-", cost: { specific: 2, free: 2 }, atk: 5 },
    { id: "A163", rank: "a", type: "action", group: "幻影旅団", nameTitle: "アクション", name: "あたしの記憶 あたしの想い", cost: { specific: 3, free: 0 }, atk: 5 },
    { id: "A200", rank: "a", type: "action", group: "幻影旅団", nameTitle: "アクション", name: "一時撤退", cost: { specific: 2, free: 0 }, atk: 5 },
    { id: "A201", rank: "b", type: "action", group: "幻影旅団", nameTitle: "アクション", name: "昼下がりのコーヒーブレイク", cost: { specific: 1, free: 0 }, atk: 5 },
    { id: "A043", rank: "ss", type: "action", group: "287期受験生", name: "親父に会いに行くんだ", cost: { specific: 2, free: 1 }, atk: 0, ability: { text: "自分の手札にあるキャラカード1枚のATKを+7する。" } },
    { id: "A044", rank: "ss", type: "action", group: "287期受験生", name: "危機一髪の救出劇", cost: { specific: 2, free: 2 }, atk: 0, ability: { text: "自分の手札にあるランダムなキャラカード2枚のATKを+5する。" } },
    { id: "A039", rank: "s", type: "action", group: "287期受験生", name: "欲情してきちゃったよ", cost: { specific: 1, free: 0 }, atk: 0, ability: { text: "自分の手札にあるキャラカード1枚のATKを+3する。" } },
    { id: "A040", rank: "s", type: "action", group: "287期受験生", name: "うちの家族とっ捕まえるんだ", cost: { specific: 1, free: 1 }, atk: 0, ability: { text: "「287期受験生」のキャラカードを1枚引く。そのカードのATKを+5する。" } },
    { id: "A041", rank: "s", type: "action", group: "287期受験生", name: "はずれて悔いなし", cost: { specific: 1, free: 2 }, atk: 0, ability: { text: "自分のHPを7回復する。" } },
    { id: "A042", rank: "s", type: "action", group: "287期受験生", name: "洞窟からの脱出", cost: { specific: 1, free: 3 }, atk: 0, ability: { text: "自分のデッキにあるキャラカード全てのATKを+2する。" } },
    { id: "A152", rank: "a", type: "action", group: "287期受験生", name: "まずは俺が行こう", cost: { specific: 1, free: 0 }, atk: 0, ability: { text: "自分の手札にあるキャラカード全てのATKを+1する。" } },
    { id: "A198", rank: "a", type: "action", group: "287期受験生", name: "いざ最終試験", cost: { specific: 3, free: 0 }, atk: 0, ability: { text: "自分のデッキにあるキャラカード全てのATKを+1する。" } },
    { id: "A199", rank: "a", type: "action", group: "287期受験生", name: "借りなんてまっぴらだ", cost: { specific: 2, free: 0 }, atk: 0, ability: { text: "自分の手札にあるカードを1枚捨てる。" } },
    { id: "A158", rank: "b", type: "action", group: "287期受験生", name: "これ一枚で十分かな", cost: { specific: 1, free: 0 }, atk: 0, ability: { text: "カードを1枚引く。" } }
];